api:
  system: "xenforo"
  url: "http://example.com/api"
  # An API-Key with auth, user:read permission
  key: "XXXX0000XXXX0000XXXX00_00XXXX000"

# Set null to use server default spawn
spawn:
  world: null
  x: null
  y: null
  z: null
teleport:
  # should tp to spawn before login in?
  tp_spawn_before_login: true
  # should tp to last quit location after login in?
  tp_back_after_login: true
secure:
  # protect information about backpack
  hide_inventory: true
  # when should show a tip
  show_tips_time: 5
  # when kick player who have not login in
  max_login_time: 30
  # do NOT touch
  cancel_chat_after_login: false
lang:
  logged_in: "§6[§1XenforoLogin§6]§1§f You have already logged in."
  success: "§6[§1XenforoLogin§6]§1§f Logged in successfully."
  need_login: "§6[§1XenforoLogin§6]§1§f Please enter your password directly in chat."
  errors:
    server: "§6[§1XenforoLogin§6]§1§f There is an issue when connecting to the server, contact the administrator."
    key: "§6[§1XenforoLogin§6]§1§f Please Check api.key [key]"
    url: "§6[§1XenforoLogin§6]§1§f Please Check api.url [url]"
    no_user: "§6[§1XenforoLogin§6]§1§f No user found."
    time_out: "§6[§1XenforoLogin§6]§1§f Login timed out!"
    name_incorrect: "§6[§1XenforoLogin§6]§1§f You should use \"[correct]\", not this to login."