name: XenforoLogin
version: ${project.version}
main: red.mohist.xenforologin.Main
api-version: 1.13
authors: [logos]
description: Support login with xenforo.
website: https://mohist.red/
softdepend: [ProtocolLib]
