api:
  # account system
  # xenforo | https://github.com/Mohist-Community/XenforoLogin/wiki/Installation-for-Xenforo
  # discuz  | https://github.com/Mohist-Community/XenforoLogin/wiki/Installation-for-Discuz
  # web     | https://github.com/Mohist-Community/XenforoLogin/wiki/Installation-for-Web
  # sqlite  | https://github.com/Mohist-Community/XenforoLogin/wiki/Installation-for-Sqlite
  # mysql   | https://github.com/Mohist-Community/XenforoLogin/wiki/Installation-for-Mysql
  system: "sqlite"
  # Can register in game
  register: true
  xenforo: # Configurations for xenforo
    url: "http://example.com/api"
    # An API-Key with auth, user:read permission
    key: "YOUR_KEY_HERE"
  discuz: # Configurations for discuz
    url: "http://example.com/XenforoLogin.php"
    # Application key
    key: "YOUR_KEY_HERE"
  web: # Configurations for WebApi
    url: "http://example.com/api.php"
    # Application key
    key: "YOUR_KEY_HERE"
  sqlite: # Configurations for sqlite
    # Path to sqlite db
    path: "Users.db"
    # is full path?
    absolute: false
    # table name in db
    table_name: "users"
    # emain field in db
    email_field: "email"
    # username field in db
    username_field: "username"
    # password field in db
    password_field: "password"
    # salt field in db(only use in password_hash need)
    salt_field: "salt"
    # salt length
    salt_length: 6
    # password hash type
    # most Recommend : BCrypt
    # https://github.com/Mohist-Community/XenforoLogin/wiki/Select-password_hash
    password_hash: "BCrypt"
  mysql: # Configurations for mysql
    # host to mysql db
    host: "localhost:3306"
    # mysql username
    username: "xenforoLogin"
    # mysql password
    password: "W8xMxJyYcxdmY33G"
    # database name
    database: "xenforoLogin"
    # table name in db
    table_name: "users"
    # emain field in db
    email_field: "email"
    # username field in db
    username_field: "username"
    # password field in db
    password_field: "password"
    # salt field in db(only use in password_hash need)
    salt_field: "salt"
    # salt length
    salt_length: 6
    # password hash type
    # most Recommend : BCrypt
    # https://github.com/Mohist-Community/XenforoLogin/wiki/Select-password_hash
    password_hash: "BCrypt"

# Set null to use server default spawn
spawn:
  world: null
  x: null
  y: null
  z: null
teleport:
  # should tp to spawn before login in?
  tp_spawn_before_login: true
  # should tp to last quit location after login in?
  tp_back_after_login: true
secure:
  # protect information about backpack
  hide_inventory: true
  # should use spectator during login?
  spectator_login: true
  # default gamemode[0,1,2,3]
  default_gamemode: 0
  # when should show a tip
  show_tips_time: 5
  # when kick player who have not login in
  max_login_time: 30
  # do NOT touch
  cancel_chat_after_login: false
lang:
  register_email: "§6[§1XenforoLogin§6]§1§f Please send your email to register."
  register_password: "§6[§1XenforoLogin§6]§1§f Please send your password."
  register_password_confirm: "§6[§1XenforoLogin§6]§1§f Please send your password again."
  logged_in: "§6[§1XenforoLogin§6]§1§f You have already logged in."
  success: "§6[§1XenforoLogin§6]§1§f Logged in successfully."
  need_login: "§6[§1XenforoLogin§6]§1§f Please enter your password directly in chat."
  errors:
    email: "§6[§1XenforoLogin§6]§1§f Wrong Email."
    server: "§6[§1XenforoLogin§6]§1§f There is an issue when connecting to the server, contact the administrator."
    confirm: "§6[§1XenforoLogin§6]§1§f You send the different password."
    handle: "§6[§1XenforoLogin§6]§1§f Sorry,We will finish your request soon.If it takes too much time,contact the administrator."
    password: "§6[§1XenforoLogin§6]§1§f Wrong password."
    key: "§6[§1XenforoLogin§6]§1§f Please Check api.key [key]"
    url: "§6[§1XenforoLogin§6]§1§f Please Check api.url [url]"
    no_user: "§6[§1XenforoLogin§6]§1§f No user found."
    time_out: "§6[§1XenforoLogin§6]§1§f Login timed out!"
    name_incorrect: "§6[§1XenforoLogin§6]§1§f You should use \"[correct]\", not this to login."
    unknown: "§6[§1XenforoLogin§6]§1§f Unknown error.Web send \"[message]\""
    mail_exist: "§6[§1XenforoLogin§6]§1§f Email have registered.Try another?"
    user_exist: "§6[§1XenforoLogin§6]§1§f Username have registered.Try another?"