name: XenforoLogin
version: ${project.version}
main: red.mohist.xenforologin.bukkit.BukkitLoader
authors:
  - logos
  - ishland
description: Support login with xenforo.
website: https://mohist.red/
softdepend: [ProtocolLib]
